### ISSUE TITLE
Blatt 4 Aufgabe 2 (Tic-Tac-Toe)

### ISSUE THREAD

**Issue by 20jmx02** [Destinyphoenix/hka_prog1#20]
![image](https://github.com/user-attachments/assets/c5a47e74-2c51-4253-b983-6c1d982456c9)

**Comment by Destinyphoenix** [comment]
![Blatt4_a2_storyboard.pdf](https://github.com/user-attachments/files/17903936/Blatt4_a2_storyboard.pdf)
